### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by naternguyen** [xiaoiker/GCN-NAS#10]
main.py:546: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  default_arg = yaml.load(f)
log_dir:  ./runs/ntu_cv_agcn_joint_Srch_CTN already exist
delete it? y/n:y
Dir removed:  ./runs/ntu_cv_agcn_joint_Srch_CTN
Refresh the website of tensorboard by pressing any keys
output device: 0

Parameters:
{'work_dir': './work_dir/ntu/xset/agcn_joint_Srch_CTN', 'model_saved_name': './runs/ntu_cv_agcn_joint_Srch_CTN', 'config': './config/nturgbd-cross-view/train_joint.yaml', 'phase': 'train', 'save_score': False, 'seed': 1, 'log_interval': 100, 'save_interval': 2, 'eval_interval': 5, 'print_log': True, 'show_topk': [1, 5], 'feeder': 'feeders.feeder.Feeder', 'num_worker': 32, 'train_feeder_args': {'data_path': './data/ntu/xset/train_data_joint.npy', 'label_path': './data/ntu/xset/train_label.pkl', 'debug': False, 'random_choose': True, 'random_shift': False, 'random_move': False, 'window_size': 270, 'normalization': False}, 'test_feeder_args': {'data_path': './data/ntu/xset/val_data_joint.npy', 'label_path': './data/ntu/xset/val_label.pkl'}, 'model': 'model.agcn3.Model', 'model_args': {'num_class': 60, 'num_point': 25, 'num_person': 2, 'graph': 'graph.ntu_rgb_d.Graph', 'graph_args': {'labeling_mode': 'spatial'}}, 'weights': '', 'ignore_weights': [], 'base_lr': 0.1, 'step': [30, 45, 60], 'device': [0], 'optimizer': 'SGD', 'nesterov': True, 'batch_size': 80, 'test_batch_size': 40, 'start_epoch': 0, 'num_epoch': 70, 'weight_decay': 0.0006, 'only_train_part': False, 'only_train_epoch': 0, 'warm_up_epoch': 0}

Training epoch: 1
Traceback (most recent call last):
  File "main.py", line 557, in <module>
    processor.start()
  File "main.py", line 498, in start
    self.train(epoch, save_model=save_model)
  File "main.py", line 365, in train
    output = self.model(data)
  File "/home/tungna/.conda/envs/nate_tffer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tungna/workspace/GCN-NAS/model/agcn3.py", line 709, in forward
    x = self.l8(x)
  File "/home/tungna/.conda/envs/nate_tffer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tungna/workspace/GCN-NAS/model/agcn3.py", line 619, in forward
    x = self.tcn1(self.gcn1(x)) + self.residual(x)
  File "/home/tungna/.conda/envs/nate_tffer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tungna/workspace/GCN-NAS/model/agcn3.py", line 49, in forward
    x = self.bn(self.conv(x))
  File "/home/tungna/.conda/envs/nate_tffer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tungna/.conda/envs/nate_tffer/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Problem:** I have run the "python main.py --config ./config/nturgbd-cross-view/train_joint.yaml --device 0"  and got this problem.
Could you tell me how can I fix it?

**Comment by xiaoiker** [comment]
Hello,

Thanks for your interest, please refer to this issue:
https://github.com/xiaoiker/GCN-NAS/issues/7#issue-626949625
