### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70

### ISSUE THREAD

**Issue by naternguyen** [xiaoiker/GCN-NAS#11]
Traceback (most recent call last):
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/queues.py", line 345, in get
    return _ForkingPickler.loads(res)
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/tungna/.conda/envs/tor_gcn/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
  0%|▋                                                                                                                                                                     | 10/2485 [00:11<49:26,  1.20s/it]
Traceback (most recent call last):
  File "main.py", line 557, in <module>
    processor.start()
  File "main.py", line 503, in start
    loader_name=['test'])
  File "main.py", line 449, in eval
    score_frag.append(output.data.cpu().numpy())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70

I have run training with " python main.py --config ./config/nturgbd-cross-view/train_joint.yaml --device 0 --batch-size 24 --test-batch-size 24" 

![image](https://user-images.githubusercontent.com/56057082/84008348-b6872280-a9ac-11ea-8910-2ff4faf757e7.png)

Could you tell me how can I solve this?

**Comment by naternguyen** [comment]
![image](https://user-images.githubusercontent.com/56057082/84009102-c2271900-a9ad-11ea-89b8-73aee63c6837.png)

It happens the same with train()

**Comment by xiaoiker** [comment]
Hey,

I am not sure what is the problem. It seems there are something wrong with your cuda or libaries. Many possible reason can cause this kind of problem. Also check here: https://github.com/pytorch/pytorch/issues/1204

Best,
